[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3.11 -m venv /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = ". /opt/venv/bin/activate && python main.py"
